-- DROP TABLE IF EXISTS abouts;
CREATE TABLE abouts (
  id INTEGER PRIMARY KEY,
  name TEXT, ht TEXT, sign TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER boom BEFORE UPDATE ON abouts BEGIN
  UPDATE abouts SET updated_at = CURRENT_TIMESTAMP WHERE id = new.id;
END;